#!/bin/bash

rm -rf build

TARGET=nahao

xcodebuild -configuration "Release" -target ${TARGET} -sdk iphoneos clean
xcodebuild -configuration "Release" -target ${TARGET} -sdk iphoneos 

APP_PATH=build/Release-iphoneos

IPA_PATH=~/Desktop/${TARGET}.`date +"%Y.%m.%d.%H.%M.%S"`.ipa
xcrun -sdk iphoneos PackageApplication -v ${APP_PATH}/${TARGET}.app -o ${IPA_PATH}

rm -rf build

open ~/Desktop/